# Generated by Django 5.1.7 on 2025-03-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresult',
            name='model',
            field=models.CharField(choices=[('GPT_4O_AUDIO_PREVIEW', 'gpt-4o-audio-preview')], default='gpt-4o-audio-preview', max_length=255),
        ),
    ]
